name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: submission_test
      id: submission_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: submission_test
        setup-command: sudo -H pip3 install --upgrade pip; sudo -H pip3 install setuptools;
          sudo -H pip3 install -U -r requirements.txt
        command: pytest
        timeout: 60
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUBMISSION_TEST_RESULTS: "${{steps.submission_test.outputs.result}}"
      with:
        runners: submission_test
